// This file is auto-generated by @hey-api/openapi-ts

export const $models_Address = {
    type: 'object',
    required: ['city', 'state', 'street', 'zip'],
    properties: {
        apt: {
            type: 'string'
        },
        city: {
            type: 'string'
        },
        state: {
            type: 'string'
        },
        street: {
            type: 'string'
        },
        zip: {
            type: 'string'
        }
    }
} as const;

export const $models_Order = {
    type: 'object',
    required: ['products', 'status', 'tracking'],
    properties: {
        createdAt: {
            type: 'string'
        },
        deletedAt: {
            type: 'string'
        },
        id: {
            type: 'string'
        },
        products: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/models.Product'
            }
        },
        status: {
            type: 'string'
        },
        total: {
            type: 'number'
        },
        tracking: {
            type: 'string'
        },
        updatedAt: {
            type: 'string'
        },
        userID: {
            type: 'string'
        }
    }
} as const;

export const $models_Product = {
    type: 'object',
    required: ['image', 'name', 'price', 'quantity', 'size'],
    properties: {
        id: {
            type: 'string'
        },
        image: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        price: {
            type: 'number'
        },
        quantity: {
            type: 'integer'
        },
        size: {
            type: 'string'
        }
    }
} as const;

export const $models_Reward = {
    type: 'object',
    required: ['code', 'description', 'image', 'name', 'validTil'],
    properties: {
        code: {
            type: 'string'
        },
        createdAt: {
            type: 'string'
        },
        deletedAt: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        id: {
            type: 'string'
        },
        image: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        pointsCost: {
            type: 'integer'
        },
        redeemed: {
            type: 'boolean'
        },
        redeemedAt: {
            type: 'string'
        },
        updatedAt: {
            type: 'string'
        },
        validTil: {
            type: 'string'
        }
    }
} as const;

export const $models_User = {
    type: 'object',
    required: ['address', 'email', 'name', 'password', 'phone'],
    properties: {
        address: {
            '$ref': '#/components/schemas/models.Address'
        },
        createdAt: {
            type: 'string'
        },
        deletedAt: {
            type: 'string'
        },
        email: {
            type: 'string'
        },
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        orders: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/models.Order'
            }
        },
        password: {
            type: 'string'
        },
        phone: {
            type: 'string'
        },
        points: {
            type: 'integer'
        },
        rewards: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/models.Reward'
            }
        },
        updatedAt: {
            type: 'string'
        }
    }
} as const;