// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { GetApiV1AccountByIdData, GetApiV1AccountByIdResponse, PutApiV1AccountByIdData, PutApiV1AccountByIdResponse, DeleteApiV1AccountByIdData, DeleteApiV1AccountByIdResponse, GetApiV1AccountByIdOrdersData, GetApiV1AccountByIdOrdersResponse, GetApiV1AccountByIdPointsData, GetApiV1AccountByIdPointsResponse, GetApiV1AccountByIdRewardsData, GetApiV1AccountByIdRewardsResponse, PostApiV1AccountByIdRewardsRedeemData, PostApiV1AccountByIdRewardsRedeemResponse, PostApiV1AuthSigninEmailData, PostApiV1AuthSigninEmailResponse, PostApiV1AuthSigninPhoneData, PostApiV1AuthSigninPhoneResponse, PostApiV1AuthSignoutResponse, PostApiV1AuthSignupData, PostApiV1AuthSignupResponse, PostApiV1WebhooksShopifyData, PostApiV1WebhooksShopifyResponse, PostApiV1WebhooksStripeData, PostApiV1WebhooksStripeResponse } from './types.gen';

export class UserService {
    /**
     * Get user details
     * Retrieves the profile information, orders, and rewards for the authenticated user.
     * @param data The data for the request.
     * @param data.id User ID
     * @returns models_User User details
     * @throws ApiError
     */
    public static getApiV1AccountById(data: GetApiV1AccountByIdData): CancelablePromise<GetApiV1AccountByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/account/{id}',
            path: {
                id: data.id
            },
            errors: {
                401: 'Unauthorized',
                404: 'User not found',
                500: 'Internal server error'
            }
        });
    }
    
    /**
     * Update user details
     * Updates the profile information for the authenticated user.
     * @param data The data for the request.
     * @param data.id User ID
     * @param data.requestBody User object with updated fields
     * @returns string message: User details updated successfully
     * @throws ApiError
     */
    public static putApiV1AccountById(data: PutApiV1AccountByIdData): CancelablePromise<PutApiV1AccountByIdResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/account/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                400: 'Invalid request body',
                401: 'Unauthorized',
                500: 'Internal server error'
            }
        });
    }
    
    /**
     * Delete user account
     * Deletes the account of the authenticated user.
     * @param data The data for the request.
     * @param data.id User ID
     * @returns string No Content
     * @throws ApiError
     */
    public static deleteApiV1AccountById(data: DeleteApiV1AccountByIdData): CancelablePromise<DeleteApiV1AccountByIdResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/account/{id}',
            path: {
                id: data.id
            },
            errors: {
                401: 'Unauthorized',
                500: 'Internal server error'
            }
        });
    }
    
    /**
     * Get user orders
     * Retrieves a paginated list of orders for the authenticated user.
     * @param data The data for the request.
     * @param data.id User ID
     * @param data.page Page number for pagination (default: 1)
     * @param data.pageSize Number of items per page (default: 5)
     * @returns models_Order orders: List of user orders
     * @throws ApiError
     */
    public static getApiV1AccountByIdOrders(data: GetApiV1AccountByIdOrdersData): CancelablePromise<GetApiV1AccountByIdOrdersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/account/{id}/orders',
            path: {
                id: data.id
            },
            query: {
                page: data.page,
                pageSize: data.pageSize
            },
            errors: {
                401: 'Unauthorized',
                500: 'Internal server error'
            }
        });
    }
    
    /**
     * Get user points
     * Retrieves the current points balance for the authenticated user.
     * @param data The data for the request.
     * @param data.id User ID
     * @returns number points: User's points balance
     * @throws ApiError
     */
    public static getApiV1AccountByIdPoints(data: GetApiV1AccountByIdPointsData): CancelablePromise<GetApiV1AccountByIdPointsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/account/{id}/points',
            path: {
                id: data.id
            },
            errors: {
                401: 'Unauthorized',
                404: 'User not found',
                500: 'Internal server error'
            }
        });
    }
    
    /**
     * Get user rewards
     * Retrieves a list of rewards redeemed by the authenticated user.
     * @param data The data for the request.
     * @param data.id User ID
     * @returns models_Reward List of user rewards
     * @throws ApiError
     */
    public static getApiV1AccountByIdRewards(data: GetApiV1AccountByIdRewardsData): CancelablePromise<GetApiV1AccountByIdRewardsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/account/{id}/rewards',
            path: {
                id: data.id
            },
            errors: {
                401: 'Unauthorized',
                500: 'Internal server error'
            }
        });
    }
    
    /**
     * Redeem a reward
     * Allows an authenticated user to redeem a reward using their points.
     * @param data The data for the request.
     * @param data.id User ID
     * @param data.requestBody Reward ID to redeem
     * @returns string message: Reward redeemed successfully
     * @throws ApiError
     */
    public static postApiV1AccountByIdRewardsRedeem(data: PostApiV1AccountByIdRewardsRedeemData): CancelablePromise<PostApiV1AccountByIdRewardsRedeemResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/account/{id}/rewards/redeem',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                400: 'Invalid request body or not enough points',
                401: 'Unauthorized',
                404: 'Reward not found',
                500: 'Internal server error'
            }
        });
    }
    
}

export class AuthenticationService {
    /**
     * Sign in with email
     * Authenticates a user using their email and password, returning a JWT.
     * @param data The data for the request.
     * @param data.requestBody User email and password
     * @returns string token and callback URL
     * @throws ApiError
     */
    public static postApiV1AuthSigninEmail(data: PostApiV1AuthSigninEmailData): CancelablePromise<PostApiV1AuthSigninEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/auth/signin/email',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                400: 'Invalid request body or validation error',
                401: 'Invalid credentials',
                500: 'Internal server error'
            }
        });
    }
    
    /**
     * Sign in with phone
     * Authenticates a user using their phone number and password, returning a JWT.
     * @param data The data for the request.
     * @param data.requestBody User phone and password
     * @returns string token and callback URL
     * @throws ApiError
     */
    public static postApiV1AuthSigninPhone(data: PostApiV1AuthSigninPhoneData): CancelablePromise<PostApiV1AuthSigninPhoneResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/auth/signin/phone',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                400: 'Invalid request body or validation error',
                401: 'Invalid credentials',
                500: 'Internal server error'
            }
        });
    }
    
    /**
     * Sign out
     * Invalidates the user's session or token (if applicable).
     * @returns string message: Signed out successfully
     * @throws ApiError
     */
    public static postApiV1AuthSignout(): CancelablePromise<PostApiV1AuthSignoutResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/auth/signout'
        });
    }
    
    /**
     * Register a new user
     * Creates a new user account with the provided details.
     * @param data The data for the request.
     * @param data.requestBody User object to register
     * @returns string message: User created successfully
     * @throws ApiError
     */
    public static postApiV1AuthSignup(data: PostApiV1AuthSignupData): CancelablePromise<PostApiV1AuthSignupResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/auth/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                400: 'Invalid request body or validation error',
                500: 'Internal server error'
            }
        });
    }
    
}

export class ShopifyService {
    /**
     * Handle Shopify webhooks
     * Receives and processes Shopify webhook events (orders/paid, orders/fulfilled, orders/updated).
     * @param data The data for the request.
     * @param data.xShopifyHmacSha256 Shopify webhook signature
     * @param data.xShopifyTopic Shopify webhook topic
     * @param data.xShopifyShopDomain Shopify shop domain
     * @param data.requestBody Webhook payload
     * @returns string OK
     * @throws ApiError
     */
    public static postApiV1WebhooksShopify(data: PostApiV1WebhooksShopifyData): CancelablePromise<PostApiV1WebhooksShopifyResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/webhooks/shopify',
            headers: {
                'X-Shopify-Hmac-Sha256': data.xShopifyHmacSha256,
                'X-Shopify-Topic': data.xShopifyTopic,
                'X-Shopify-Shop-Domain': data.xShopifyShopDomain
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                400: 'Bad Request',
                401: 'Unauthorized',
                405: 'Method Not Allowed'
            }
        });
    }
    
}

export class StripeService {
    /**
     * Handle Stripe webhooks
     * Receives and processes Stripe webhook events (charge.succeeded, payment_intent.succeeded, invoice.payment_succeeded).
     * @param data The data for the request.
     * @param data.stripeSignature Stripe webhook signature
     * @param data.requestBody Webhook payload
     * @returns string OK
     * @throws ApiError
     */
    public static postApiV1WebhooksStripe(data: PostApiV1WebhooksStripeData): CancelablePromise<PostApiV1WebhooksStripeResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/webhooks/stripe',
            headers: {
                'Stripe-Signature': data.stripeSignature
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                400: 'Bad Request',
                401: 'Unauthorized',
                405: 'Method Not Allowed'
            }
        });
    }
    
}