// This file is auto-generated by @hey-api/openapi-ts

export type handlers_SignUpEmailCreds = {
  email?: string;
  password?: string;
};

export type handlers_SignUpPhoneCreds = {
  password?: string;
  phone?: string;
};

export type models_Address = {
  apt?: string;
  city: string;
  state: string;
  street: string;
  zip: string;
};

export type models_Order = {
  createdAt?: string;
  deletedAt?: string;
  id?: string;
  products: Array<models_Product>;
  status: string;
  total?: number;
  tracking: string;
  updatedAt?: string;
  userID?: string;
};

export type models_Product = {
  id?: string;
  image: string;
  name: string;
  price: number;
  quantity: number;
  size: string;
};

export type models_Reward = {
  code: string;
  createdAt?: string;
  deletedAt?: string;
  description: string;
  id?: string;
  image: string;
  name: string;
  pointsCost?: number;
  redeemed?: boolean;
  redeemedAt?: string;
  updatedAt?: string;
  validTil: string;
};

export type models_User = {
  address: models_Address;
  createdAt?: string;
  deletedAt?: string;
  email: string;
  id?: string;
  name: string;
  orders?: Array<models_Order>;
  phone: string;
  points?: number;
  rewards?: Array<models_Reward>;
  updatedAt?: string;
};

export type GetApiV1AccountByIdData = {
  /**
   * User ID
   */
  id: string;
};

export type GetApiV1AccountByIdResponse = models_User;

export type PutApiV1AccountByIdData = {
  /**
   * User ID
   */
  id: string;
  /**
   * User object with updated fields
   */
  requestBody: models_User;
};

export type PutApiV1AccountByIdResponse = {
  [key: string]: string;
};

export type DeleteApiV1AccountByIdData = {
  /**
   * User ID
   */
  id: string;
};

export type DeleteApiV1AccountByIdResponse = string;

export type GetApiV1AccountByIdOrdersData = {
  /**
   * User ID
   */
  id: string;
  /**
   * Page number for pagination (default: 1)
   */
  page?: number;
  /**
   * Number of items per page (default: 5)
   */
  pageSize?: number;
};

export type GetApiV1AccountByIdOrdersResponse = {
  [key: string]: Array<models_Order>;
};

export type GetApiV1AccountByIdPointsData = {
  /**
   * User ID
   */
  id: string;
};

export type GetApiV1AccountByIdPointsResponse = {
  [key: string]: number;
};

export type GetApiV1AccountByIdRewardsData = {
  /**
   * User ID
   */
  id: string;
};

export type GetApiV1AccountByIdRewardsResponse = Array<models_Reward>;

export type PostApiV1AccountByIdRewardsRedeemData = {
  /**
   * User ID
   */
  id: string;
  /**
   * Reward ID to redeem
   */
  requestBody: {
    [key: string]: string;
  };
};

export type PostApiV1AccountByIdRewardsRedeemResponse = {
  [key: string]: string;
};

export type PostApiV1AuthSigninEmailData = {
  /**
   * User email and password
   */
  requestBody: handlers_SignUpEmailCreds;
};

export type PostApiV1AuthSigninEmailResponse = {
  [key: string]: string;
};

export type PostApiV1AuthSigninPhoneData = {
  /**
   * User phone and password
   */
  requestBody: handlers_SignUpPhoneCreds;
};

export type PostApiV1AuthSigninPhoneResponse = {
  [key: string]: string;
};

export type PostApiV1AuthSignoutResponse = {
  [key: string]: string;
};

export type PostApiV1AuthSignupData = {
  /**
   * User object to register
   */
  requestBody: models_User;
};

export type PostApiV1AuthSignupResponse = {
  [key: string]: string;
};

export type PostApiV1WebhooksShopifyData = {
  /**
   * Webhook payload
   */
  requestBody: unknown;
  /**
   * Shopify webhook signature
   */
  xShopifyHmacSha256: string;
  /**
   * Shopify shop domain
   */
  xShopifyShopDomain: string;
  /**
   * Shopify webhook topic
   */
  xShopifyTopic: string;
};

export type PostApiV1WebhooksShopifyResponse = string;

export type PostApiV1WebhooksStripeData = {
  /**
   * Webhook payload
   */
  requestBody: unknown;
  /**
   * Stripe webhook signature
   */
  stripeSignature: string;
};

export type PostApiV1WebhooksStripeResponse = string;

export type $OpenApiTs = {
  "/api/v1/account/{id}": {
    get: {
      req: GetApiV1AccountByIdData;
      res: {
        /**
         * User details
         */
        200: models_User;
        /**
         * Unauthorized
         */
        401: string;
        /**
         * User not found
         */
        404: string;
        /**
         * Internal server error
         */
        500: string;
      };
    };
    put: {
      req: PutApiV1AccountByIdData;
      res: {
        /**
         * message: User details updated successfully
         */
        200: {
          [key: string]: string;
        };
        /**
         * Invalid request body
         */
        400: string;
        /**
         * Unauthorized
         */
        401: string;
        /**
         * Internal server error
         */
        500: string;
      };
    };
    delete: {
      req: DeleteApiV1AccountByIdData;
      res: {
        /**
         * No Content
         */
        204: string;
        /**
         * Unauthorized
         */
        401: string;
        /**
         * Internal server error
         */
        500: string;
      };
    };
  };
  "/api/v1/account/{id}/orders": {
    get: {
      req: GetApiV1AccountByIdOrdersData;
      res: {
        /**
         * orders: List of user orders
         */
        200: {
          [key: string]: Array<models_Order>;
        };
        /**
         * Unauthorized
         */
        401: string;
        /**
         * Internal server error
         */
        500: string;
      };
    };
  };
  "/api/v1/account/{id}/points": {
    get: {
      req: GetApiV1AccountByIdPointsData;
      res: {
        /**
         * points: User's points balance
         */
        200: {
          [key: string]: number;
        };
        /**
         * Unauthorized
         */
        401: string;
        /**
         * User not found
         */
        404: string;
        /**
         * Internal server error
         */
        500: string;
      };
    };
  };
  "/api/v1/account/{id}/rewards": {
    get: {
      req: GetApiV1AccountByIdRewardsData;
      res: {
        /**
         * List of user rewards
         */
        200: Array<models_Reward>;
        /**
         * Unauthorized
         */
        401: string;
        /**
         * Internal server error
         */
        500: string;
      };
    };
  };
  "/api/v1/account/{id}/rewards/redeem": {
    post: {
      req: PostApiV1AccountByIdRewardsRedeemData;
      res: {
        /**
         * message: Reward redeemed successfully
         */
        200: {
          [key: string]: string;
        };
        /**
         * Invalid request body or not enough points
         */
        400: string;
        /**
         * Unauthorized
         */
        401: string;
        /**
         * Reward not found
         */
        404: string;
        /**
         * Internal server error
         */
        500: string;
      };
    };
  };
  "/api/v1/auth/signin/email": {
    post: {
      req: PostApiV1AuthSigninEmailData;
      res: {
        /**
         * token and callback URL
         */
        200: {
          [key: string]: string;
        };
        /**
         * Invalid request body or validation error
         */
        400: string;
        /**
         * Invalid credentials
         */
        401: string;
        /**
         * Internal server error
         */
        500: string;
      };
    };
  };
  "/api/v1/auth/signin/phone": {
    post: {
      req: PostApiV1AuthSigninPhoneData;
      res: {
        /**
         * token and callback URL
         */
        200: {
          [key: string]: string;
        };
        /**
         * Invalid request body or validation error
         */
        400: string;
        /**
         * Invalid credentials
         */
        401: string;
        /**
         * Internal server error
         */
        500: string;
      };
    };
  };
  "/api/v1/auth/signout": {
    post: {
      res: {
        /**
         * message: Signed out successfully
         */
        200: {
          [key: string]: string;
        };
      };
    };
  };
  "/api/v1/auth/signup": {
    post: {
      req: PostApiV1AuthSignupData;
      res: {
        /**
         * message: User created successfully
         */
        201: {
          [key: string]: string;
        };
        /**
         * Invalid request body or validation error
         */
        400: string;
        /**
         * Internal server error
         */
        500: string;
      };
    };
  };
  "/api/v1/webhooks/shopify": {
    post: {
      req: PostApiV1WebhooksShopifyData;
      res: {
        /**
         * OK
         */
        200: string;
        /**
         * Bad Request
         */
        400: string;
        /**
         * Unauthorized
         */
        401: string;
        /**
         * Method Not Allowed
         */
        405: string;
      };
    };
  };
  "/api/v1/webhooks/stripe": {
    post: {
      req: PostApiV1WebhooksStripeData;
      res: {
        /**
         * OK
         */
        200: string;
        /**
         * Bad Request
         */
        400: string;
        /**
         * Unauthorized
         */
        401: string;
        /**
         * Method Not Allowed
         */
        405: string;
      };
    };
  };
};
