import type { Metadata } from "next";
import { Navbar } from "@/components/layout/navbar";
import { IBM_Plex_Mono } from "next/font/google";
import "./globals.css";
import { Footer } from "@/components/layout/footer";
import { ReactQueryProvider } from "@/components/providers/react-query-provider";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "BVR STR SHOP",
  description: "Generated by create next app",
};

const ibm = IBM_Plex_Mono({
  variable: "--font-ibm-plex-mono",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ibm.variable} antialiased`}>
        <ReactQueryProvider>
          <Navbar />
          <Toaster />
          {children}
          <Footer />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
