import type { Metadata } from "next";
import { Navbar } from "@/components/layout/navbar";
import { IBM_Plex_Mono } from "next/font/google";
import "./globals.css";
import { Footer } from "@/components/layout/footer";
import { ReactQueryProvider } from "@/components/providers/react-query-provider";
import { Toaster } from "sonner";
import { cookies } from "next/headers";
import { getCart } from "@/lib/shopify";
import { CartProvider } from "@/components/cart/cart-context";
import { getCollections } from "@/lib/shopify";

export const metadata: Metadata = {
  title: "BVR STR SHOP",
  description: "Generated by create next app",
  robots: {
    follow: true,
    index: true,
  },
};

const ibm = IBM_Plex_Mono({
  variable: "--font-ibm-plex-mono",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cartId = (await cookies()).get("cartId")?.value;
  // Don't await the fetch, pass the Promise to the context provider
  const cart = getCart(cartId);

  const collections = await getCollections();
  return (
    <html lang="en">
      <body className={`${ibm.variable} antialiased`}>
        <ReactQueryProvider>
          <CartProvider cartPromise={cart}>
            <Navbar collections={collections} />
            <main>
              {children}
              <Toaster closeButton />
            </main>
            <Footer />
          </CartProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
