/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BVR STR User API
 * API for BVR STR user management and rewards system
 * OpenAPI spec version: 1.0
 */
import type { ModelsOrder } from './modelsOrder';

export type GetApiV1AccountIdOrders200 = {[key: string]: ModelsOrder[]};
