/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BVR STR User API
 * API for BVR STR user management and rewards system
 * OpenAPI spec version: 1.0
 */

export type GetApiV1AccountIdOrdersParams = {
/**
 * Page number for pagination (default: 1)
 */
page?: number;
/**
 * Number of items per page (default: 5)
 */
pageSize?: number;
};
