/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BVR STR User API
 * API for BVR STR user management and rewards system
 * OpenAPI spec version: 1.0
 */
import type { ModelsProduct } from './modelsProduct';

export interface ModelsOrder {
  createdAt?: string;
  deletedAt?: string;
  id?: string;
  products: ModelsProduct[];
  status: string;
  total?: number;
  tracking: string;
  updatedAt?: string;
  userID?: string;
}
