/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BVR STR User API
 * API for BVR STR user management and rewards system
 * OpenAPI spec version: 1.0
 */

export interface ModelsAddress {
  apt?: string;
  city: string;
  state: string;
  street: string;
  zip: string;
}
