/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BVR STR User API
 * API for BVR STR user management and rewards system
 * OpenAPI spec version: 1.0
 */

export interface ModelsReward {
  code: string;
  createdAt?: string;
  deletedAt?: string;
  description: string;
  id?: string;
  image: string;
  name: string;
  pointsCost?: number;
  redeemed?: boolean;
  redeemedAt?: string;
  updatedAt?: string;
  validTil: string;
}
