/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BVR STR User API
 * API for BVR STR user management and rewards system
 * OpenAPI spec version: 1.0
 */

export interface ModelsProduct {
  id?: string;
  image: string;
  name: string;
  price: number;
  quantity: number;
  size: string;
}
